server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: h4ckm3
    key-alias: exchange
#server:
#  port: 8050
spring:
  application:
    name: smart-exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_exchange
    username: ramiro
    password: h4ckm3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
---
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expiration: 240 #min 60 1 hora
  confirm:
    expiration: 120 #min
  refresh:
    expiration: 15 #min
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: artilugio.productions.tech@gmail.com
    password: 'hhbg hxon pyuh gghp'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true