#server:
#  port: 443
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.app.lc-exchange.com.p12
#    key-store-password: h4ckm3
    ##################key-alias: artilugioproductions.com
server:
  port: 8050
spring:
  application:
    name: smart-exchange
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-exchange
    username: postgres #lcexchange
    password: h4ckm3 #Lc-3xch4ng32024.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
---
jwt:
  secret: secrets3cretsecr3ts3cr3tsecr3tsecrets3crets3cret
  expiration: 30 #min 60 1 hora
  confirm:
    expiration: 120 #min
  refresh:
    expiration: 40 #min
---
spring:
  mail:
    host: mail.lc-exchange.com
    port: 465
    username: operaciones@lc-exchange.com
    password: ',u?ur5.wKJ$k'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: artilugio.productions.tech@gmail.com
#    password: 'hhbg hxon pyuh gghp'
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true