server:
  port: 8050
spring:
  application:
    name: account-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-exchange
    username: postgres
    password: h4ckm3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
---
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expiration: 30
  confirm:
    expiration: 60
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: artilugio.productions.tech@gmail.com
    password: 'hhbg hxon pyuh gghp'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true